import abb from "images/Abb.png";
import rabite from "images/rabite.png";
import pasha from "images/pasha.png";
import kapital from "images/kapital.png";
import turan from "images/turan.png";
import gunayBank from "images/gunaybank.png";
import uniBank from "images/unibank.png";
import chevron from "images/chevron.png";

export const BankInformation = [
  {
    img: abb,
    text: "ABB",
  },
  {
    img: rabite,
    text: "Rabitə Bank",
  },
  {
    img: pasha,
    text: "Paşa Bank",
  },
  {
    img: kapital,
    text: "Kapital Bank",
  },
  {
    img: turan,
    text: "Turan Bank",
  },
  {
    img: gunayBank,
    text: "Günay Bank",
  },
  {
    img: uniBank,
    text: "UniBank",
  },
];

export const Cards = [
  {
    id: "1",
    title: "Satılıb",
    area: "246kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "2",
    title: "Kredit",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "3",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "4",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "5",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "6",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "7",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "8",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "9",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "10",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "11",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "12",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "13",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "14",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "15",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "16",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "17",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "18",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "19",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "20",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "21",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "22",
    title: "Kredit",
    area: "144kv",
    sup: "2",
    room: "4 otaqlı",
    link: " Ətraflı",
    color: "#FDA242",
    secondcolor: "#FDA242",
  },
  {
    id: "23",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "24",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "25",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "26",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "27",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "28",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "29",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "30",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "31",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "32",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
  {
    id: "33",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "34",
    title: "Ipoteka",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#3B7EA4",
    secondcolor: "#3B7EA4",
  },
  {
    id: "35",
    title: "Satılıb",
    area: "94kv",
    sup: "2",
    room: "3 otaqlı",
    link: " Ətraflı",
    color: "#9C89CE",
    secondcolor: "#5E44A2",
  },
];

export const CustomerData = [
  {
    id: "1",
    customer: "Niyaz Əliyev",
    building: "20",
    cost: "40.000 AZN",
    statuscolor: "var(--late-color)",
    statustitle: "var(--late-title)",
    status: "Gecikir",
    lastdate: "Son ödəmə tarixi",
    lastpayment: "20.07.2020",
    first_payment: "İlkin ödəniş",
    firspayment: "28.000 AZN",
    month_payment: "Aylıq ödəniş",
    monthlypayment: "700 AZN",
    duration_status: "Müddəti",
    duration: "Ödənilib",
    chevron: chevron,
    button: "Bildiriş göndər",
  },
  {
    id: "2",
    customer: "Əli Ağayev",
    building: "19",
    cost: "70.000 AZN",
    status: "Ödənilib",
    statuscolor: "var(--green)",
    statustitle: "var(--dark-green)",
    lastdate: "Son ödəmə tarixi",
    lastpayment: "20.07.2020",
    first_payment: "İlkin ödəniş",
    firspayment: "28.000 AZN",
    month_payment: "Aylıq ödəniş",
    monthlypayment: "700 AZN",
    duration_status: "Müddəti",
    duration: "Ödənilib",
    chevron: chevron,
    button: "Bildiriş göndər",
  },
  {
    id: "3",
    customer: "Murad Nağıyev",
    building: "18",
    cost: "60.000 AZN",
    status: "Ödənilib",
    statuscolor: "var(--green)",
    statustitle: "var(--dark-green)",
    lastdate: "Son ödəmə tarixi",
    lastpayment: "20.07.2020",
    first_payment: "İlkin ödəniş",
    firspayment: "28.000 AZN",
    month_payment: "Aylıq ödəniş",
    monthlypayment: "700 AZN",
    duration_status: "Müddəti",
    duration: "Ödənilib",
    chevron: chevron,
    button: "Bildiriş göndər",
  },
  {
    id: "4",
    customer: "Niyaz Əliyev",
    building: "17",
    cost: "50.000 AZN",
    status: "Gecikir",
    statuscolor: "var(--late-color)",
    statustitle: "var(--late-title)",
    lastdate: "Son ödəmə tarixi",
    lastpayment: "20.07.2020",
    first_payment: "İlkin ödəniş",
    firspayment: "28.000 AZN",
    month_payment: "Aylıq ödəniş",
    monthlypayment: "700 AZN",
    duration_status: "Müddəti",
    duration: "Ödənilib",
    chevron: chevron,
    button: "Bildiriş göndər",
  },
  {
    id: "5",
    customer: "Niyaz Əliyev",
    building: "15",
    cost: "60.000 AZN",
    status: "Ödənilib",
    statuscolor: "var(--green)",
    statustitle: "var(--dark-green)",
    lastdate: "Son ödəmə tarixi",
    lastpayment: "20.07.2020",
    first_payment: "İlkin ödəniş",
    firspayment: "28.000 AZN",
    month_payment: "Aylıq ödəniş",
    monthlypayment: "700 AZN",
    duration_status: "Müddəti",
    duration: "Ödənilib",
    chevron: chevron,
    button: "Bildiriş göndər",
  },
  {
    id: "6",
    customer: "Niyaz Əliyev",
    building: "20",
    cost: "40.000 AZN",
    status: "Gecikir",
    statuscolor: "var(--late-color)",
    statustitle: "var(--late-title)",
    lastdate: "Son ödəmə tarixi",
    lastpayment: "20.07.2020",
    first_payment: "İlkin ödəniş",
    firspayment: "28.000 AZN",
    month_payment: "Aylıq ödəniş",
    monthlypayment: "700 AZN",
    duration_status: "Müddəti",
    duration: "Ödənilib",
    chevron: chevron,
    button: "Bildiriş göndər",
  },
  {
    id: "7",
    customer: "Niyaz Əliyev",
    building: "14",
    cost: "40.000 AZN",
    status: "Ödənilib",
    statuscolor: "var(--green)",
    statustitle: "var(--dark-green)",
    lastdate: "Son ödəmə tarixi",
    lastpayment: "20.07.2020",
    first_payment: "İlkin ödəniş",
    firspayment: "28.000 AZN",
    month_payment: "Aylıq ödəniş",
    monthlypayment: "700 AZN",
    duration_status: "Müddəti",
    duration: "Ödənilib",
    chevron: chevron,
    button: "Bildiriş göndər",
  },
];
